"""
Volume → image rendering.

The 3-view projection logic is lifted **verbatim** from benchmark/testset.py so
rendered frames match the reference images in data/examples/ (which were
generated by that pipeline). Any deviation creates a domain gap between the
current frame and the in-prompt references.

The on-disk render cache makes full-loop evals tolerable on rerun: TIFF→JPEG is
the dominant cost, and the cache is content-addressed on (path, mtime, params).
"""
from __future__ import annotations

import base64
import hashlib
import io
import json
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np
import tifffile
from PIL import Image

# Bumping this invalidates every cached render — do so when projection logic changes.
RENDER_PARAMS_VERSION = 2  # v2: parity with benchmark/testset.py

_REPO_ROOT = Path(__file__).resolve().parents[2]
_CACHE_DIR = _REPO_ROOT / "data" / "render_cache"

# Light-sheet voxel spacing (Z, Y, X) — Z is coarser than the lateral plane.
VOXEL_SIZE = (1.0, 0.1625, 0.1625)


@dataclass(frozen=True)
class RenderParams:
    max_dim: int = 1500
    jpeg_quality: int = 90


DEFAULT_PARAMS = RenderParams()


# --- Loading & normalization ------------------------------------------------


def load_volume(path: Path) -> np.ndarray:
    """Load a 3D (Z, Y, X) volume from TIFF or NPZ.

    Real Shroff-lab TIFFs are (1, Z, Y, X) — leading singleton dims are squeezed.
    Dual-view TIFFs (width > 2× height) keep View A only.
    """
    path = Path(path)
    if path.suffix == ".npz":
        with np.load(path) as f:
            arr = f[f.files[0]]
    else:
        arr = tifffile.imread(path)
    arr = np.squeeze(arr)
    if arr.ndim == 3:
        z, h, w = arr.shape
        if w > h * 2:
            arr = arr[:, :, : w // 2]
    assert arr.ndim == 3, f"expected 3D volume after squeeze, got {arr.shape}"
    return arr


def normalize(arr: np.ndarray, *, p_low: float = 1.0, p_high: float = 99.0) -> np.ndarray:
    """Percentile-stretch to uint8. Matches benchmark/testset.py:_normalize_image."""
    arr = arr.astype(np.float32)
    vmin, vmax = np.percentile(arr, [p_low, p_high])
    if vmax > vmin:
        arr = np.clip((arr - vmin) / (vmax - vmin), 0, 1)
    else:
        arr = np.zeros_like(arr)
    return (arr * 255).astype(np.uint8)


def crop_bounds(volume: np.ndarray, *, padding: int = 20, sigma_mult: float = 3.5) -> tuple[int, int, int, int]:
    """Center-of-mass auto-crop bounds. Matches benchmark/testset.py:_compute_crop_bounds."""
    if volume.ndim != 3:
        return (0, volume.shape[0], 0, volume.shape[1])
    max_proj = np.max(volume, axis=0).astype(np.float32)
    threshold = np.percentile(max_proj, 95)
    mask = max_proj > threshold
    y_coords, x_coords = np.where(mask)
    if len(y_coords) < 10:
        return (0, volume.shape[1], 0, volume.shape[2])
    cy, cx = float(np.mean(y_coords)), float(np.mean(x_coords))
    y_std = max(float(np.std(y_coords)), 20.0)
    x_std = max(float(np.std(x_coords)), 20.0)
    y_min = int(max(0, cy - sigma_mult * y_std - padding))
    y_max = int(min(volume.shape[1], cy + sigma_mult * y_std + padding))
    x_min = int(max(0, cx - sigma_mult * x_std - padding))
    x_max = int(min(volume.shape[2], cx + sigma_mult * x_std + padding))
    return (y_min, y_max, x_min, x_max)


# --- Projections ------------------------------------------------------------


def project_axis(volume: np.ndarray, view: str) -> np.ndarray:
    """Max-intensity projection along one axis. view ∈ {xy, yz, xz}."""
    match view:
        case "xy":
            return volume.max(axis=0)
        case "yz":
            return volume.max(axis=2).T  # (Z, Y) → (Y, Z)
        case "xz":
            return volume.max(axis=1)  # (Z, X)
        case _:
            raise ValueError(f"unknown view {view!r}")


def three_view(volume: np.ndarray, voxel_size: tuple[float, float, float] = VOXEL_SIZE) -> np.ndarray:
    """3-view layout matching benchmark/testset.py:_projection_three_view.

    [XY | YZ] top row, [XZ] bottom row. Z axis stretched by physical voxel ratio.
    """
    z_depth, height, width = volume.shape
    dz, dy, dx = voxel_size

    xy_proj = normalize(np.max(volume, axis=0))
    xz_proj = normalize(np.max(volume, axis=1))
    yz_proj = normalize(np.max(volume, axis=2))

    xy_h, xy_w = xy_proj.shape
    z_scale = dz / dx
    xz_display_h = max(1, int(z_depth * z_scale))

    pil_xz = Image.fromarray(xz_proj).resize((xy_w, xz_display_h), Image.Resampling.LANCZOS)
    xz_scaled = np.array(pil_xz)

    yz_rotated = yz_proj.T
    yz_display_w = xz_display_h
    pil_yz = Image.fromarray(yz_rotated).resize((yz_display_w, xy_h), Image.Resampling.LANCZOS)
    yz_scaled = np.array(pil_yz)

    sep = 3
    v_sep = np.ones((xy_h, sep), dtype=np.uint8) * 128
    top_row = np.concatenate([xy_proj, v_sep, yz_scaled], axis=1)
    total_width = top_row.shape[1]

    if xz_scaled.shape[1] < total_width:
        pad = np.zeros((xz_scaled.shape[0], total_width - xz_scaled.shape[1]), dtype=np.uint8)
        bottom_row = np.concatenate([xz_scaled, pad], axis=1)
    else:
        bottom_row = xz_scaled[:, :total_width]

    h_sep = np.ones((sep, total_width), dtype=np.uint8) * 128
    return np.concatenate([top_row, h_sep, bottom_row], axis=0)


# --- Encoding & cache -------------------------------------------------------


def array_to_b64(arr: np.ndarray, *, target_long_edge: int = 1500, quality: int = 90) -> str:
    """Normalize (if not uint8), resize so long edge ≤ target, encode as base64 JPEG."""
    arr8 = arr if arr.dtype == np.uint8 else normalize(arr)
    img = Image.fromarray(arr8)
    if max(img.size) > target_long_edge:
        scale = target_long_edge / max(img.size)
        img = img.resize((int(img.width * scale), int(img.height * scale)), Image.Resampling.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=quality)
    return base64.b64encode(buf.getvalue()).decode("ascii")


def render(volume: np.ndarray, params: RenderParams = DEFAULT_PARAMS) -> str:
    """Volume → base64 3-view JPEG. Matches benchmark/testset.py:_create_three_view_image."""
    y0, y1, x0, x1 = crop_bounds(volume)
    cropped = volume[:, y0:y1, x0:x1]
    canvas = three_view(cropped)  # already uint8 from per-projection normalize
    return array_to_b64(canvas, target_long_edge=params.max_dim, quality=params.jpeg_quality)


def _cache_key(path: Path, params: RenderParams, extra: dict | None = None) -> str:
    payload = {
        "path": str(path),
        "mtime": path.stat().st_mtime if path.exists() else 0,
        "params": asdict(params),
        "version": RENDER_PARAMS_VERSION,
        "extra": extra or {},
    }
    return hashlib.sha256(json.dumps(payload, sort_keys=True).encode()).hexdigest()


def cached_render(path: Path, params: RenderParams = DEFAULT_PARAMS) -> str:
    """Render with on-disk cache. Returns base64 JPEG."""
    _CACHE_DIR.mkdir(parents=True, exist_ok=True)
    key = _cache_key(Path(path), params)
    cache_file = _CACHE_DIR / f"{key}.b64"
    if cache_file.exists():
        return cache_file.read_text()
    b64 = render(load_volume(path), params)
    cache_file.write_text(b64)
    return b64


def cached_tool_result(
    path: Path, tool_name: str, params: dict, compute, *, suffix: str = "b64"
) -> str:
    """Generic content-addressed cache for tool outputs keyed on (volume, tool, params)."""
    _CACHE_DIR.mkdir(parents=True, exist_ok=True)
    key = _cache_key(Path(path), DEFAULT_PARAMS, extra={"tool": tool_name, "args": params})
    cache_file = _CACHE_DIR / f"{key}.{suffix}"
    if cache_file.exists():
        return cache_file.read_text()
    result = compute()
    cache_file.write_text(result)
    return result
